### ISSUE TITLE
Rate limited on the GH API when trying to `landr build`

### ISSUE THREAD

**Issue by phil-d-wilson** [product-os/landr#500]
➜  blocks git:(docs-update) ✗ landr build
[landr] gathering git reference information...
[landr] generating data for ./ on branch docs-update...
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/config/.nvm/versions/node/v12.22.10/lib/node_modules/landr/node_modules/@octokit/request-error/dist-node/index.js:57:21)
    at Object.prettyPrint [as default] (/config/.nvm/versions/node/v12.22.10/lib/node_modules/landr/node_modules/@oclif/errors/lib/errors/pretty-print.js:31:22)
    at Object.exports.handle (/config/.nvm/versions/node/v12.22.10/lib/node_modules/landr/node_modules/@oclif/errors/lib/handle.js:18:46)
    at module.exports (/config/.nvm/versions/node/v12.22.10/lib/node_modules/landr/node_modules/@oclif/errors/handle.js:1:49)
    HttpError: API rate limit exceeded for 149.102.2.156. (But here's the good news: Authenticated requests get a higher rate limit. Check out the 
    documentation for more details.)
    Code: 403

**Comment by andrewnhem** [comment]
@phil-d-wilson not a permanent fix but a workaround for now-- if you create a GH oauth token and run that with your landr commands, it should work.

@iamsolankiamit What's our plan for this again for both teammates and external users? Is "you need an oauth token bc you'll be constantly grabbing data from GH" just part of reality and expectation that we need to set up front?

**Comment by iamsolankiamit** [comment]
@andrewnhem we have reduced our reliance on Github api, but we still fetch some data which is only available from Github. Using landr locally without the token should be fine normally, but if you try to run it multiple times it will hit the limit. Github provides quite high limit when using their token. 

Using your Github token is the only way to avoid this for local build. As landr by design needs to access github.
